[package]
name = "memfd-exec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tempfile = "3.2.0"

[dependencies]
nix = "0.25.0"
libc = "0.2.134"
